### ISSUE TITLE
Port the Biblio - Crossref submodule

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/biblio#12]
Placeholder issue for PR.

**Comment by juanolalla** [comment]
Pull request: https://github.com/juanolalla/biblio/pull/1

**Comment by jenlampton** [comment]
Can you update the PR so that it is against the contrib project? I don't have access to do that.

**Comment by juanolalla** [comment]
Closed the PR, opened a new one against the contrib project: https://github.com/backdrop-contrib/biblio/pull/19

**Comment by jenlampton** [comment]
PR https://github.com/backdrop-contrib/biblio/pull/19 merged, closing.
