### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column

### ISSUE THREAD

**Issue by suardus** [backdrop-contrib/biblio#20]
Hi

I'm new to backdrop. Before actualy migrate my drupal7 site (https://labyrinth.rienkjonker.nl) to backdrop, i'm perfoming some tests. I have just installed the biblio module. When i try to save content this error message is popping up: 
Error SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_biblio_authors_field_biblio_person_tid' in 'field list'

Is there a solution?

**Comment by jenlampton** [comment]
Hi @suardus,

It sounds like either the Multifield field "Person", or the taxonomy "Biblio author" may be missing from your site. Can you check that both of those things exist? 

Did you install the module on a fresh Backdrop install, or on an upgraded version of your Drupal 7 site?

**Comment by suardus** [comment]
Hi @jenlampton 

I tried a new fresh install of Backdrop (https://testersatz.rienkjonker.nl/). After installing the module and its dependencies the same error message came up. 
It seems that both the Multifield field "Person"  and the taxonomy "Biblio author" are missing. See the attached file/
[20240221_Biblio_Error_SQLSTATE_42S22.pdf](https://github.com/backdrop-contrib/biblio/files/14356993/20240221_Biblio_Error_SQLSTATE_42S22.pdf)

**Comment by jenlampton** [comment]
That's strange, if the config exists then the database structure that supports the field should be created at the time the config is imported. We should look into this.

**Comment by jenlampton** [comment]
Biblio was using a custom import order that may have been causing this problem. I have removed that to let core do it's (now) usual config import which should fix this problem. 🤞 

This fix is in the latest release: https://github.com/backdrop-contrib/biblio/releases/tag/1.x-2.0.1
