### ISSUE TITLE
Status report page won't load due to drupal_get_schema

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/biblio#3]
The status report page isn't loading for me with this module enabled, due to a stray drupal_get_schema. This pull request fixes it: https://github.com/backdrop-contrib/biblio/pull/2

**Comment by olafgrabienski** [comment]
Interesting! I'm just testing Biblio for the first time, and the Status report page is loading fine (without using the fix).  #2 has been merged.

**Comment by jenlampton** [comment]
@olafgrabienski I think the problem will only occur if you disable the Drupal compatibility layer in `settings.php`.
