### ISSUE TITLE
Submodules: 'type' attribute in info files missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/biblio#5]
I tried to install the module via the Backdrop UI using the "Manual installation". Installation failed with the following message:

> The info file (temporary://SOME-FOLDER/biblio-1.x-2.x/modules/rtf/biblio_rtf.info) does not define a 'type' attribute.

On further investigation I saw that all the `.info` files of submodules don't have a 'type' attribute.

**Comment by olafgrabienski** [comment]
After changing all the `.info` files in the folders listed below, I was able to install the module via the "Manual installation" UI option. I've replaced the line:

`core = 7.x`

with these:

`version = 1.x-1.x`
`type = module`
`backdrop = 1.x`

---

- modules/bibtexParse
- modules/CiteProc
- modules/crossref
- modules/endnote
- modules/marcParse
- modules/pubmed
- modules/RIS
- modules/rtf

**Comment by stpaultim** [comment]
I installed this module and got this:

![biblio](https://user-images.githubusercontent.com/3144571/107135775-285c9680-68c3-11eb-8f7f-812f8c86397e.png)

**Comment by stpaultim** [comment]
I did a quick PR that I think solves this problem. Just testing it now. 

I'm a bit confused, because I can only find a 1.x-2.x branch, so I updated .info files to reflect this and create my PR against that branch. https://github.com/backdrop-contrib/biblio/pull/9

**Comment by stpaultim** [comment]
This looks better?

![biblio-2](https://user-images.githubusercontent.com/3144571/107136040-8be7c380-68c5-11eb-9534-ffd7d42ba932.png)

**Comment by stpaultim** [comment]
Ah, I found same [problem in another module](https://github.com/backdrop-contrib/styleguide/issues/1#issuecomment-76297623) and you (@jenlampton) said:

> I don't think styleguide_palette has been ported to Backdrop yet. At least, I haven't been working on it. I think we should get a full port before we update the info file. I'll update the title to be a more accurate todo item.

These submodules are probably in the same unported state, which is why the .info file is not updated.

**Comment by jenlampton** [comment]
For unported sub-modules I usually add a note in the README and add `hidden = true` to the info file to keep them off the module page until they are ready.

My project didn't need any of the submodules (obviously), all bilbio content was imported only from Zotero. I'd love help with PRs as other people find that the other submodules are needed.

**Comment by jenlampton** [comment]
Here's an issue where people can weigh in on submodules: https://github.com/backdrop-contrib/biblio/issues/10

**Comment by jenlampton** [comment]
I've committed a change that adds `hidden = true` to each submodule's info file, along with a link to the issue about porting submodules. I've also added `type = module` to each file (since I was in there anyway). That should resolve this issue.
