### ISSUE TITLE
Call to undefined function with Bib-Tex submodule

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/biblio#7]
After enabling the *Biblio - Bibtex* module, I got the following error:

`Call to undefined function biblio_save_map() in _save_bibtex_maps() (line 144 of /PATH-TO/modules/biblio-1.x-2.x/modules/bibtexParse/biblio_bibtex.install).`

(IIRC, the enabling success message was missing instead, but the submodule was however enabled.)

**Comment by jenlampton** [comment]
This module has not been ported yet, so this problem is likely a duplicate of https://github.com/backdrop-contrib/biblio/issues/1
