### ISSUE TITLE
[META] Release blockers

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/biblio#8]
@jenlampton - Just a reminder that there is no official release for this yet. Is it ready?

---

- [x] Problems caused by un-ported submodules #5

**Comment by jenlampton** [comment]
There's no upgrade path yet, but we can add that later. I can make a 2.0.0 release and add the upgrade in 1.1.x :)

**Comment by stpaultim** [comment]
I just realized that the sub-modules are probably not ported yet, which may be another reason why you were reluctant to push a full release. 

https://github.com/backdrop-contrib/biblio/issues/5

**Comment by jenlampton** [comment]
I still think we can publish a 2.0.0 since this module should work "as is" for new installations. We can add newly ported submodules as they become available. 

https://github.com/backdrop-contrib/biblio/releases/tag/1.x-2.0.0
